#
# Copyright (C) 2017-2020 Alibaba Group Holding Limited
#
# SPDX-License-Identifier: GPL-2.0+
#

obj-y += c910_ice.o

obj-$(CONFIG_SPL_BUILD) += gpio/gpio.o
obj-$(CONFIG_SPL_BUILD) += spl/spl.o
obj-$(CONFIG_SPL_BUILD) += spl/ddr.o
obj-$(CONFIG_SPL_BUILD) += om/om.o

