/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RISCV-Unified-Discovery"
 * 	found in "discoverdata.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "DiscoveryAdditonalData.h"

static asn_per_constraints_t asn_PER_type_tag_constr_2 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_numeric_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DiscoveryAdditonalData__tag__numeric, manufacturer),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_JEDEC_ID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"manufacturer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DiscoveryAdditonalData__tag__numeric, identifier),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"identifier"
		},
};
static const ber_tlv_tag_t asn_DEF_numeric_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_numeric_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* manufacturer */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* identifier */
};
static asn_SEQUENCE_specifics_t asn_SPC_numeric_specs_5 = {
	sizeof(struct DiscoveryAdditonalData__tag__numeric),
	offsetof(struct DiscoveryAdditonalData__tag__numeric, _asn_ctx),
	asn_MAP_numeric_tag2el_5,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_numeric_5 = {
	"numeric",
	"numeric",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_numeric_tags_5,
	sizeof(asn_DEF_numeric_tags_5)
		/sizeof(asn_DEF_numeric_tags_5[0]) - 1, /* 1 */
	asn_DEF_numeric_tags_5,	/* Same as above */
	sizeof(asn_DEF_numeric_tags_5)
		/sizeof(asn_DEF_numeric_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_numeric_5,
	2,	/* Elements count */
	&asn_SPC_numeric_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_tag_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DiscoveryAdditonalData__tag, choice.oid),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"oid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DiscoveryAdditonalData__tag, choice.url),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"url"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DiscoveryAdditonalData__tag, choice.numeric),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_numeric_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"numeric"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_tag_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* oid */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* url */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* numeric */
};
static asn_CHOICE_specifics_t asn_SPC_tag_specs_2 = {
	sizeof(struct DiscoveryAdditonalData__tag),
	offsetof(struct DiscoveryAdditonalData__tag, _asn_ctx),
	offsetof(struct DiscoveryAdditonalData__tag, present),
	sizeof(((struct DiscoveryAdditonalData__tag *)0)->present),
	asn_MAP_tag_tag2el_2,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_tag_2 = {
	"tag",
	"tag",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_tag_constr_2,
	asn_MBR_tag_2,
	3,	/* Elements count */
	&asn_SPC_tag_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_DiscoveryAdditonalData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DiscoveryAdditonalData, tag),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_tag_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tag"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DiscoveryAdditonalData, payload),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"payload"
		},
};
static const ber_tlv_tag_t asn_DEF_DiscoveryAdditonalData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DiscoveryAdditonalData_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* tag */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* payload */
};
static asn_SEQUENCE_specifics_t asn_SPC_DiscoveryAdditonalData_specs_1 = {
	sizeof(struct DiscoveryAdditonalData),
	offsetof(struct DiscoveryAdditonalData, _asn_ctx),
	asn_MAP_DiscoveryAdditonalData_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DiscoveryAdditonalData = {
	"DiscoveryAdditonalData",
	"DiscoveryAdditonalData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DiscoveryAdditonalData_tags_1,
	sizeof(asn_DEF_DiscoveryAdditonalData_tags_1)
		/sizeof(asn_DEF_DiscoveryAdditonalData_tags_1[0]), /* 1 */
	asn_DEF_DiscoveryAdditonalData_tags_1,	/* Same as above */
	sizeof(asn_DEF_DiscoveryAdditonalData_tags_1)
		/sizeof(asn_DEF_DiscoveryAdditonalData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DiscoveryAdditonalData_1,
	2,	/* Elements count */
	&asn_SPC_DiscoveryAdditonalData_specs_1	/* Additional specs */
};

