/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_DiscoveryData;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module RISCV-Unified-Discovery in discoverdata.asn */
	&asn_DEF_DiscoveryData,	
	0
};

