/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RISCV-Unified-Discovery"
 * 	found in "discoverdata.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_DiscoveryData_H_
#define	_DiscoveryData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RVVConfig;
struct DiscoveryErrata;
struct DiscoveryAdditonalData;

/* DiscoveryData */
typedef struct DiscoveryData {
	long	 version;
	struct DiscoveryData__errata {
		A_SEQUENCE_OF(struct DiscoveryErrata) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *errata;
	struct DiscoveryData__ext {
		A_SEQUENCE_OF(struct DiscoveryAdditonalData) list;

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct DiscoveryData__c {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *c;
	struct DiscoveryData__d {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *d;
	struct DiscoveryData__f {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *f;
	struct DiscoveryData__h {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *h;
	struct DiscoveryData__m {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *m;
	struct DiscoveryData__n {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *n;
	struct DiscoveryData__q {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *q;
	struct DiscoveryData__p {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *p;
	struct DiscoveryData__sdext {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sdext;
	struct DiscoveryData__sdtrig {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sdtrig;
	struct DiscoveryData__shcounterenw {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *shcounterenw;
	struct DiscoveryData__shgatpa {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *shgatpa;
	struct DiscoveryData__shtvala {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *shtvala;
	struct DiscoveryData__shvsatpa {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *shvsatpa;
	struct DiscoveryData__shvstvala {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *shvstvala;
	struct DiscoveryData__shvstvecd {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *shvstvecd;
	struct DiscoveryData__sm1p11 {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sm1p11;
	struct DiscoveryData__sm1p12 {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sm1p12;
	struct DiscoveryData__sm1p13 {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sm1p13;
	struct DiscoveryData__smaia {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *smaia;
	struct DiscoveryData__smclic {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *smclic;
	struct DiscoveryData__smcdeleg {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *smcdeleg;
	struct DiscoveryData__smcntrpmf {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *smcntrpmf;
	struct DiscoveryData__smcsrind {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *smcsrind;
	struct DiscoveryData__smepmp {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *smepmp;
	struct DiscoveryData__smrnmi {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *smrnmi;
	struct DiscoveryData__smmpm {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *smmpm;
	struct DiscoveryData__smrntt {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *smrntt;
	struct DiscoveryData__smnpm {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *smnpm;
	struct DiscoveryData__smstateen {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *smstateen;
	struct DiscoveryData__ss1p11 {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ss1p11;
	struct DiscoveryData__ss1p12 {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ss1p12;
	struct DiscoveryData__ss1p13 {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ss1p13;
	struct DiscoveryData__ssaia {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ssaia;
	struct DiscoveryData__ssccfg {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ssccfg;
	struct DiscoveryData__ssccptr {

		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ssccptr;
	struct DiscoveryData__sscofpmf {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sscofpmf;
	struct DiscoveryData__sscounterenw {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sscounterenw;
	struct DiscoveryData__sscsrind {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sscsrind;
	struct DiscoveryData__ssdtso {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ssdtso;
	struct DiscoveryData__ssnpm {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ssnpm;
	struct DiscoveryData__ssstateeen {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ssstateeen;
	struct DiscoveryData__sstc {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sstc;
	struct DiscoveryData__sstvala {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sstvala;
	struct DiscoveryData__sstvecd {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sstvecd;
	struct DiscoveryData__sstvecv {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sstvecv;
	struct DiscoveryData__ssu32xl {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ssu32xl;
	struct DiscoveryData__ssu64xl {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ssu64xl;
	struct DiscoveryData__ssube {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ssube;
	struct DiscoveryData__sv32 {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sv32;
	struct DiscoveryData__sv39 {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sv39;
	struct DiscoveryData__sv48 {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sv48;
	struct DiscoveryData__sv57 {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sv57;
	struct DiscoveryData__svade {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *svade;
	struct DiscoveryData__svadu {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *svadu;
	struct DiscoveryData__svbare {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *svbare;
	struct DiscoveryData__svinval {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *svinval;
	struct DiscoveryData__svnapot {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *svnapot;
	struct DiscoveryData__svpbmt {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *svpbmt;
	struct RVVConfig	*rvv	/* OPTIONAL */;
	struct DiscoveryData__za128rs {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *za128rs;
	struct DiscoveryData__za64rs {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *za64rs;
	struct DiscoveryData__zaamo {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zaamo;
	struct DiscoveryData__zacas {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zacas;
	struct DiscoveryData__zalrsc {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zalrsc;
	struct DiscoveryData__zawrs {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zawrs;
	struct DiscoveryData__zba {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zba;
	struct DiscoveryData__zbb {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zbb;
	struct DiscoveryData__zbc {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zbc;
	struct DiscoveryData__zbkb {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zbkb;
	struct DiscoveryData__zbkc {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zbkc;
	struct DiscoveryData__zbkx {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zbkx;
	struct DiscoveryData__zbs {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zbs;
	struct DiscoveryData__zca {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zca;
	struct DiscoveryData__zcb {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zcb;
	struct DiscoveryData__zcd {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zcd;
	struct DiscoveryData__zcf {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zcf;
	struct DiscoveryData__zcmp {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zcmp;
	struct DiscoveryData__zcmt {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zcmt;
	struct DiscoveryData__zdinx {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zdinx;
	struct DiscoveryData__zfa {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zfa;
	struct DiscoveryData__zfbfmin {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zfbfmin;
	struct DiscoveryData__zfh {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zfh;
	struct DiscoveryData__zfhmin {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zfhmin;
	struct DiscoveryData__zfinx {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zfinx;
	struct DiscoveryData__zhinx {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zhinx;
	struct DiscoveryData__zhinxmin {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zhinxmin;
	struct DiscoveryData__zic64b {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zic64b;
	struct DiscoveryData__zicbom {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zicbom;
	struct DiscoveryData__zicbop {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zicbop;
	struct DiscoveryData__zicboz {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zicboz;
	struct DiscoveryData__ziccamoa {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ziccamoa;
	struct DiscoveryData__ziccif {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ziccif;
	struct DiscoveryData__zicclsm {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zicclsm;
	struct DiscoveryData__ziccrse {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ziccrse;
	struct DiscoveryData__zicntr {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zicntr;
	struct DiscoveryData__zicond {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zicond;
	struct DiscoveryData__zicsr {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zicsr;
	struct DiscoveryData__zifencei {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zifencei;
	struct DiscoveryData__zihintntl {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zihintntl;
	struct DiscoveryData__zihintpause {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zihintpause;
	struct DiscoveryData__zihpm {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zihpm;
	struct DiscoveryData__zimop {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zimop;
	struct DiscoveryData__zjid {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zjid;
	struct DiscoveryData__zk {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zk;
	struct DiscoveryData__zkn {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zkn;
	struct DiscoveryData__zknd {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zknd;
	struct DiscoveryData__zkne {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zkne;
	struct DiscoveryData__zknh {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zknh;
	struct DiscoveryData__zkr {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zkr;
	struct DiscoveryData__zks {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zks;
	struct DiscoveryData__zksed {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zksed;
	struct DiscoveryData__zksh {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zksh;
	struct DiscoveryData__zkt {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zkt;
	struct DiscoveryData__zmmul {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zmmul;
	struct DiscoveryData__ztso {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ztso;
	struct DiscoveryData__zvbb {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvbb;
	struct DiscoveryData__zvbc {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvbc;
	struct DiscoveryData__zve32d {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zve32d;
	struct DiscoveryData__zve32f {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zve32f;
	struct DiscoveryData__zve32x {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zve32x;
	struct DiscoveryData__zve64d {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zve64d;
	struct DiscoveryData__zve64f {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zve64f;
	struct DiscoveryData__zve64x {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zve64x;
	struct DiscoveryData__zvf {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvf;
	struct DiscoveryData__zvfbfmin {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvfbfmin;
	struct DiscoveryData__zvfbfwma {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvfbfwma;
	struct DiscoveryData__zvfh {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvfh;
	struct DiscoveryData__zvfhmin {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvfhmin;
	struct DiscoveryData__zvk {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvk;
	struct DiscoveryData__zvkb {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvkb;
	struct DiscoveryData__zvkg {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvkg;
	struct DiscoveryData__zvkn {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvkn;
	struct DiscoveryData__zvknc {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvknc;
	struct DiscoveryData__zvkned {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvkned;
	struct DiscoveryData__zvkng {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvkng;
	struct DiscoveryData__zvknha {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvknha;
	struct DiscoveryData__zvknhb {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvknhb;
	struct DiscoveryData__zvks {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvks;
	struct DiscoveryData__zvksc {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvksc;
	struct DiscoveryData__zvksed {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvksed;
	struct DiscoveryData__zvksg {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvksg;
	struct DiscoveryData__zvksh {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvksh;
	struct DiscoveryData__zvkt {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *zvkt;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DiscoveryData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DiscoveryData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RVVConfig.h"
#include "DiscoveryErrata.h"
#include "DiscoveryAdditonalData.h"

#endif	/* _DiscoveryData_H_ */
#include <asn_internal.h>
