/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RISCV-Unified-Discovery"
 * 	found in "discoverdata.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_DiscoveryAdditonalData_H_
#define	_DiscoveryAdditonalData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <OBJECT_IDENTIFIER.h>
#include <UTF8String.h>
#include "JEDEC-ID.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DiscoveryAdditonalData__tag_PR {
	DiscoveryAdditonalData__tag_PR_NOTHING,	/* No components present */
	DiscoveryAdditonalData__tag_PR_oid,
	DiscoveryAdditonalData__tag_PR_url,
	DiscoveryAdditonalData__tag_PR_numeric
} DiscoveryAdditonalData__tag_PR;

/* DiscoveryAdditonalData */
typedef struct DiscoveryAdditonalData {
	struct DiscoveryAdditonalData__tag {
		DiscoveryAdditonalData__tag_PR present;
		union DiscoveryAdditonalData__tag_u {
			OBJECT_IDENTIFIER_t	 oid;
			UTF8String_t	 url;
			struct DiscoveryAdditonalData__tag__numeric {
				JEDEC_ID_t	 manufacturer;
				long	 identifier;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} numeric;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} tag;
	OCTET_STRING_t	 payload;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DiscoveryAdditonalData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DiscoveryAdditonalData;

#ifdef __cplusplus
}
#endif

#endif	/* _DiscoveryAdditonalData_H_ */
#include <asn_internal.h>
