/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RISCV-Unified-Discovery"
 * 	found in "discoverdata.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_DiscoveryErrata_H_
#define	_DiscoveryErrata_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DiscoveryErrata */
typedef struct DiscoveryErrata {
	OBJECT_IDENTIFIER_t	 oid;
	UTF8String_t	*url	/* OPTIONAL */;

	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DiscoveryErrata_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DiscoveryErrata;

#ifdef __cplusplus
}
#endif

#endif	/* _DiscoveryErrata_H_ */
#include <asn_internal.h>
