/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RISCV-Unified-Discovery"
 * 	found in "discoverdata.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_RVVConfig_H_
#define	_RVVConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RVVConfig__vlen {
	RVVConfig__vlen_vlen128	= 0,
	RVVConfig__vlen_vlen256	= 1,
	RVVConfig__vlen_vlen512	= 2,
	RVVConfig__vlen_vlen1024	= 3
} e_RVVConfig__vlen;

/* RVVConfig */
typedef struct RVVConfig {
	BIT_STRING_t	 vlen;

	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RVVConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RVVConfig;

#ifdef __cplusplus
}
#endif

#endif	/* _RVVConfig_H_ */
#include <asn_internal.h>
