#
# Copyright (C) 2017-2020 Alibaba Group Holding Limited
#
# SPDX-License-Identifier: GPL-2.0+
#

obj-y := anole_c860_evb.o

ifdef CONFIG_SPL_BUILD
obj-y += spl/clock.o
obj-y += spl/ddr.o
obj-y += spl/ddr_phy.o
obj-y += spl/multi_bin.o
obj-y += spl/spl.o
endif
